### ISSUE TITLE
everytime i run the plugin model i get this error

### ISSUE THREAD

**Issue by lopatri** [neslerel/QGISRed#5] opened 2019-11-12 10:35 UTC
Error: at EPANETToolkit.EpanetToolkit.?????????????????????????????????????????.?????????????????????????????????????????(String ) at EPANETToolkit.EpanetToolkit.Iniciar(String tempDllPath) at GISRed.Model.Scenario.Compute(Logger logger, String dllDirectory) at GISRed.QGisPlugins.QGisPlugins.Compute(String dirPath, String networkName)

[teste.zip](https://github.com/neslerel/QGISRed/files/3835650/teste.zip)

**Comment by neslerel** [comment] 2019-11-12 11:15
Hi @lopatri, 
Can you tell me your QGis version and QGISRed Plugin version to analyse your issue?
Thanks!

**Comment by lopatri** [comment] 2019-11-12 12:17
Hi
Thank you for reply and congratulations. It seems to me a great Plugin 

QGisRed version 0.7
QGIS Madeira 3.4

P.S - the file i tested ran well on EPANET

best regards

**Comment by neslerel** [comment] 2019-11-12 15:10
Hi,

I tested in some diferent computers with x86 and x64 architecture with your QGISRed version and QGis 3 and I didn't issues. 
Maybe the problem is in some character of the project path or maybe in the regional configuration.
Could you tell me which is the project directory, the network name and the regional configuration of the computer (i.e., GB, EN, ES, etc.).

It would be nice to fix this bug for the next version that will be released at the end of the month with a lot of new features.

Thanks!

**Comment by lopatri** [comment] 2019-11-12 22:00
Hi
Now i've tried from home. I was in my job and maybe the error was due firewall/folder restritions 
On Qgis 2 las palmas works very nicely
On Qgis 3 Madeira i have got this error

Couldn't load plugin 'QGISRed-master' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'win32api' 
Traceback (most recent call last):
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 335, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/LMR/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QGISRed-master\__init__.py", line 34, in classFactory
    from .qgisred_plugins import QGISRed
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/LMR/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QGISRed-master\qgisred_plugins.py", line 28, in 
    from win32api import GetFileVersionInfo, LOWORD, HIWORD
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'win32api'


Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.4.2-Madeira Madeira, 22034aa070 

Python Path:
C:/OSGEO4~1/apps/qgis/./python
C:/Users/LMR/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/LMR/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/OSGEO4~1/apps/qgis/./python/plugins
C:\OSGeo4W64\bin\python37.zip
C:\OSGEO4~1\apps\Python37\DLLs
C:\OSGEO4~1\apps\Python37\lib
C:\OSGeo4W64\bin
C:\OSGEO4~1\apps\Python37
C:\OSGEO4~1\apps\Python37\lib\site-packages
C:/Users/LMR/AppData/Roaming/QGIS/QGIS3\profiles\default/python

thanks!

**Comment by neslerel** [comment] 2019-11-13 07:30
Hi @lopatri,

I'm happy that it works at your home.
I noticed that you tried to install a QGISRed-master version downloaded from this repository (?). The code of this repository is not always stable, only the releases. I recommend you only install oficial versions of the plugin directly from QGis repository (from Plugin Manager in QGis).

In QGis 2 only QGISRed version 0.6 (and 0.6.1) is available. The new versions (0.7 and nexts) are only available for QGis 3.
The next version (0.8) will incorporate new features (edit properties of the elements, move nodes, insert valves or pumps, etc.) and a new organization of the icons of the plugin for a best undertand.

If after a new installation in your job, it doesn't work, please write here to try to fix the error.

Best regards,

**Comment by lopatri** [comment] 2019-11-13 11:13
HI

After a fresh install i still get the same error

Gisred is istalled on C:\Program Files\GISRed

here in my work, when i run epanet, i have to run the executable directly from the folder where the program is installed otherwise when i run a simulation i get an error "Fileacessdenied"
Maybe is a computer configuration/restriction

network name - network
 project directory - C:\Users\1179\Desktop\QGisred
regional configuration - PT

**Comment by lopatri** [comment] 2019-11-13 11:58
Hi @neslerel 

I just executed Qgis as administrator.

Now works very well

Thank you

**Comment by neslerel** [comment] 2019-11-13 12:03
Hi @lopatri,

I was writting you when you answered again. 
Ok, if this is the problem, don't worry (I hope) because in the next version (0.8) will not be necessary administrative permission to install QGISRed dependencies and I suppose that neither to use them.

Thanks for report the issue! It is always good to improve the plugin.

**Closed** 2019-11-29 10:58 UTC
