### ISSUE TITLE
Headloss curves not imported for GPV valves

### ISSUE THREAD

**Issue by mcarvajalino** [neslerel/QGISRed#84] opened 2022-05-24 07:15 UTC
Hi, 

I received a model in .inp format where some PRVs have been modelled as GPV to include reduction pressure falloff as a QH curve (realistic pressure drop dependent on flow) in the "settings" field. However, when I import the model in QGISRed the curve names in the "settings" field disappear and it seems that I cannot input a curve name in that field, just a number. 

Maybe a bug?

Best,
Marcos

**Comment by neslerel** [comment] 2022-05-24 15:33
Hi @mcarvajalino,

Yes, it is a bug! We are going to fix it as soon as possible.

Thanks for your comment!

**Comment by neslerel** [comment] 2022-05-27 21:12
In this link you can download an **unofficial** version (0.15.3) to test it.
http://www.redhisp.webs.upv.es/files/QGISRed/QGISRed_v0.15.3.zip

To use it, you have to:
1. Uninstall the QGISRed plugin from the QGis plugin manager.
2. Close QGis
3. Go to Windows Applications and Features and uninstall the program called QGISRed (I guess version 1.0.15.0)).
4. Open QGis and go to the plugin manager.
5. Install from file (with the zip downloaded from the previous link)
6. When using it, it will ask to install the new dependencies.

Please, confirm us if it is fixed to close the issue. Thanks!

**Comment by neslerel** [comment] 2022-09-09 15:12
Hi @mcarvajalino,

Could you confirm if the issue is fixed and close this issue?

Thanks!

**Closed** 2022-09-20 11:47 UTC
Labels: bug, fixed
